/**
 * This file is auto-generated by the generate-colors.js script.
 * Do not edit this file directly.
 */

export const colors = {
  light: {
    background: "hsl(0, 0%, 100%)",
    foreground: "hsl(345, 55%, 31%)",
    card: "hsl(25, 100%, 94%)",
    cardForeground: "hsl(345, 55%, 31%)",
    popover: "hsl(0, 0%, 100%)",
    popoverForeground: "hsl(345, 55%, 31%)",
    primary: "hsl(34, 85%, 66%)",
    primaryForeground: "hsl(0, 0%, 100%)",
    secondary: "hsl(25, 100%, 94%)",
    secondaryForeground: "hsl(345, 55%, 31%)",
    muted: "hsl(25, 50%, 96%)",
    mutedForeground: "hsl(0, 0%, 47%)",
    accent: "hsl(295, 30%, 81%)",
    accentForeground: "hsl(345, 55%, 31%)",
    destructive: "hsl(0, 80%, 57.70%)",
    destructiveForeground: "hsl(0, 0%, 100%)",
    border: "hsl(25, 30%, 88%)",
    input: "hsl(25, 30%, 88%)",
    ring: "hsl(34, 85%, 66%)",
  },
  dark: {},
};
